### ISSUE TITLE
Issues setting up EoX API

### ISSUE THREAD

**Issue by thomascrha** [hoelsner/product-database#11]
After running the docker commands for getting the standalone version - just for testing, I can log into the web ui and add my client-id and client-secret. After pressing save I get this error within the `web` container. Now I'm not sure if this a bug or simply that I don't have the correct permissions/API's configured in the cisco web portal.

```
[  ERROR 19/Dec/2019 06:42:22] Cisco EoX API test access failed ('expires_in')
Traceback (most recent call last):
  File "/var/www/productdb/source/app/config/utils.py", line 44, in check_cisco_eox_api_access
    base_api.query_product("WS-C2960-24T")
  File "/var/www/productdb/source/app/ciscoeox/base_api.py", line 259, in query_product
    if self.is_ready_for_use():
  File "/var/www/productdb/source/app/ciscoeox/base_api.py", line 195, in is_ready_for_use
    self.create_temporary_access_token(force_new_token=True)
  File "/var/www/productdb/source/app/ciscoeox/base_api.py", line 156, in create_temporary_access_token
    expire_offset = datetime.timedelta(seconds=self.current_access_token['expires_in'])
KeyError: 'expires_in'
```

**Comment by hoelsner** [comment]
Hi, it should be an issue with the credentials. Have you added the permissions for EoX V5 API?
